# Generated by Django 3.2.5 on 2021-07-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_bag', '0002_auto_20210725_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='item_status',
            field=models.CharField(choices=[('BOUGHT', 'BOUGHT'), ('PENDING', 'PENDING'), ('NOT-AVAILABLE', 'NOT AVAILABLE')], default='PENDING', max_length=70),
        ),
    ]
